### PR TITLE
Make 0.3.0 release

### PR DESCRIPTION
**Pull request by michaelosthege**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelosthege** [comment]
@conda-forge-admin please rerender

**Comment by michaelosthege** [comment]
@conda-forge-admin please rerender

**Comment by michaelosthege** [comment]
@conda-forge-admin, please restart ci

**Comment by aseyboldt** [comment]
I think we probably also need to delete this, which I added for the dev build:
https://github.com/conda-forge/sunode-feedstock/pull/15/commits/4fa2597184d2e16f75359ac7c18bec55c795e65e#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2

and after that also another rerender?

**Comment by michaelosthege** [comment]
> I think we probably also need to delete this, which I added for the dev build: [4fa2597#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2](https://github.com/conda-forge/sunode-feedstock/commit/4fa2597184d2e16f75359ac7c18bec55c795e65e#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2)
> 
> and after that also another rerender?

I did that in https://github.com/conda-forge/sunode-feedstock/pull/15/commits/283a8af6e8dc2e490285277292a1e7e047b580bb, already followed by a re-render.


If the tests pass this time, I will squash the last four commits and then we should be good to go

**Comment by michaelosthege** [comment]
In the [overall PR diff](https://github.com/conda-forge/sunode-feedstock/pull/15/files) there's no `-alpha` and the SHA256 is the one for the [`.tar.gz` of the `0.3.0` release](https://github.com/aseyboldt/sunode/releases/tag/v0.3.0)

Is that not correct?

**Comment by aseyboldt** [comment]
I think we were talking about two different things. I meant the file `conda_build_config.yml`.
"No -alpha" in the path name and "the sha256 of the released tar.gz" should both be correct.

**Comment by michaelosthege** [comment]
Oh, yeah I totally overlooked that. It's gone now.

**Comment by aseyboldt** [comment]
@conda-forge-admin, please rerender

**Comment by michaelosthege** [comment]
@conda-forge-admin, please rerender

**Comment by aseyboldt** [comment]
Looks good to me

**Pull request merged**
