### PR TITLE
Add aarch64 build platform

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@aseyboldt, @michaelosthege, I think I got it! :grin:

**Review by michaelosthege — APPROVED** [review]
This looks like black magic to me. But the pipeline goes green, and I like that!

**Comment by maresb** [comment]
What do you think @aseyboldt, is this safe to merge?

**Comment by maresb** [comment]
Gentle ping @aseyboldt

**Pull request merged**
